apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness3
spec:
  containers:
  - name: liveness
    image: ubuntu
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;sleep 600
    livenessProbe:
      httpGet:
        host: bd.kubiosec.tech
        path: /?%27OR%201=1--
        port: 8080
        httpHeaders:
          - name: User-Agent
            value: hacking-demo
