apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec39
spec:
  containers:
  - name: liveness
    image: ubuntu
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;sleep 600
    readinessProbe:
      exec:
        command:
        - apt-get 
        - update
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 60
    livenessProbe:
      exec:
        command:
        - apt-get 
        - install
        - -y
        - curl
      initialDelaySeconds: 60
      periodSeconds: 100
      timeoutSeconds: 60
